{{- if .Values.victoriametrics.enabled }}
{{- if .Values.victoriametrics.vmalert.enabled }}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlert
metadata:
  name: cluster
  namespace: {{ .Release.Namespace }}
spec:
  configMaps: []
  datasource:
    url: http://vmselect-cluster.{{ .Release.Namespace }}.svc:8481/select/0/prometheus
  evaluationInterval: 15s
  externalLabels: {}
  extraArgs:
    http.pathPrefix: /
    remoteWrite.disablePathAppend: "true"
  image:
    tag: v1.105.0
  license: {}
  notifiers:
  - url: http://vmalertmanager-cluster-0.vmalertmanager-cluster.{{ .Release.Namespace }}.svc:9093/
  port: "8080"
  remoteRead:
    url: {{ .Values.victoriametrics.vmalert.remoteRead | default (printf "http://vmselect-cluster.%s.svc:8481/select/0/prometheus" .Release.Namespace) }} 
  remoteWrite:
    url: http://vminsert-cluster.{{ .Release.Namespace }}.svc:8480/insert/0/prometheus/api/v1/write
  replicaCount: {{ .Values.victoriametrics.vmalert.replicaCount }}
  resources: {{ .Values.victoriametrics.vmalert.resources | toYaml | nindent 4 }}
  selectAllByDefault: true
{{- end }}
{{- end }}
