{{- if .Values.victoriametrics.enabled }}
{{- if .Values.victoriametrics.vmauth.enabled }}
{{- if (index .Values "victoriametrics" "vmauth" | default dict).enabled | default false }}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAuth
metadata:
  name: cluster
  namespace: {{ .Release.Namespace }}
spec:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: {{ include "cert-manager.cluster-issuer.name" $ }}
      {{- include "cert-manager.acme-annotation" $ | nindent 6 }}
    class_name: nginx
    tlsHosts:
    - {{ .Values.victoriametrics.vmauth.ingress.host | quote }}
    tlsSecretName: vmauth-tls
  license: {}
  port: "8427"
  selectAllByDefault: true

  # Protecting from CVE-2019-11248 in VMAuth which exposes `/debug/pprof`
  # and a lot of other endpoints listed in https://docs.victoriametrics.com/#security
  extraArgs:
    envflag.enable: "true"
    envflag.prefix: "vm_"
  extraEnvs:
    - name: vm_httpAuth_username
      valueFrom:
        secretKeyRef:
          name: {{ .Values.victoriametrics.vmauth.credentials.credentials_secret_name }}
          key: {{ .Values.victoriametrics.vmauth.credentials.username_key }}
    - name: vm_httpAuth_password
      valueFrom:
        secretKeyRef:
          name: {{ .Values.victoriametrics.vmauth.credentials.credentials_secret_name }}
          key: {{ .Values.victoriametrics.vmauth.credentials.password_key }}
{{- end }}
{{- end }}
{{- end }}
