{{- if .Values.victoriametrics.enabled }}
{{- if .Values.victoriametrics.vmauth.enabled }}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMUser
metadata:
  name: vmuser-select
  namespace: {{ .Release.Namespace }}
spec:
  targetRefs:
  - drop_src_path_prefix_parts: 1
    paths:
    - /vls/.*
    static:
      url: http://{{ .Release.Name }}-victoria-logs-cluster-vlselect.{{ .Release.Namespace }}.svc:9471
  - drop_src_path_prefix_parts: 1
    paths:
    - /vli/.*
    static:
      url: http://{{ .Release.Name }}-victoria-logs-cluster-vlinsert.{{ .Release.Namespace }}.svc:9481
  - drop_src_path_prefix_parts: 1
    paths:
    - /vm/select/.*
    static:
      url: http://vmselect-cluster.{{ .Release.Namespace }}.svc:8481
  - drop_src_path_prefix_parts: 1
    paths:
    - /vm/insert/.*
    static:
      url: http://vminsert-cluster.{{ .Release.Namespace }}.svc:8480
{{- $secret := (lookup "v1" "Secret" .Release.Namespace .Values.victoriametrics.vmauth.credentials.credentials_secret_name) }}
{{- if not $.Values.global.lint }}
  username: {{ index $secret.data .Values.victoriametrics.vmauth.credentials.username_key | b64dec | quote }}
{{- end }}
  passwordRef:
    key: {{ .Values.victoriametrics.vmauth.credentials.password_key }}
    name: {{ .Values.victoriametrics.vmauth.credentials.credentials_secret_name }}
{{- end }}
{{- end }}
