apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ClusterDeployment
metadata:
  name: aws-ue2
  namespace: kcm-system
  labels:
    k0rdent.mirantis.com/istio-role: child
    k0rdent.mirantis.com/kof-cluster-role: regional
spec:
  credential: aws-cluster-identity-cred
  template: aws-standalone-cp-0-1-2
  config:
    clusterIdentity:
      name: aws-cluster-identity
      namespace: kcm-system
    controlPlane:
      instanceType: t3.large
    controlPlaneNumber: 1
    publicIP: false
    region: us-east-2
    worker:
      instanceType: t3.medium
    workersNumber: 3
