apiVersion: k0rdent.mirantis.com/v1beta1
kind: ClusterDeployment
metadata:
  name: aws-ue2-istio-child
  namespace: kcm-system
  labels:
    k0rdent.mirantis.com/istio-role: child
    k0rdent.mirantis.com/kof-cluster-role: child
spec:
  template: aws-standalone-cp-0-2-0
  credential: aws-cluster-identity-cred
  config:
    clusterIdentity:
      name: aws-cluster-identity
      namespace: kcm-system

    region: us-east-2

    controlPlaneNumber: 1
    controlPlane:
      instanceType: t3.large

    workersNumber: 3
    worker:
      instanceType: t3.medium
