apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ClusterDeployment
metadata:
  name: aws-ue2
  namespace: kcm-system
  labels:
    k0rdent.mirantis.com/kof-storage-secrets: "true"
    k0rdent.mirantis.com/kof-aws-dns-secrets: "true"
    k0rdent.mirantis.com/kof-cluster-role: regional
spec:
  credential: aws-cluster-identity-cred
  template: aws-standalone-cp-0-1-5
  config:
    clusterAnnotations:
      k0rdent.mirantis.com/kof-regional-domain: aws-ue2.kof.example.com
      k0rdent.mirantis.com/kof-cert-email: mail@example.com

      # `template: aws-standalone-cp` provides a default storage class:
      # k0rdent.mirantis.com/kof-storage-class: ebs-csi-default-sc

      # Default endpoints for `kof-regional-domain: aws-ue2.kof.example.com`:
      # kof-write-metrics-endpoint: https://vmauth.aws-ue2.kof.example.com/vm/insert/0/prometheus/api/v1/write
      # kof-read-metrics-endpoint: https://vmauth.aws-ue2.kof.example.com/vm/select/0/prometheus
      # kof-write-logs-endpoint: https://vmauth.aws-ue2.kof.example.com/vls/insert/opentelemetry/v1/logs
      # kof-read-logs-endpoint: https://vmauth.aws-ue2.kof.example.com/vls
      # kof-write-traces-endpoint: https://jaeger.aws-ue2.kof.example.com/collector
    clusterIdentity:
      name: aws-cluster-identity
      namespace: kcm-system
    controlPlane:
      instanceType: t3.large
    controlPlaneNumber: 1
    publicIP: false
    region: us-east-2
    worker:
      instanceType: t3.medium
    workersNumber: 3
