apiVersion: k0rdent.mirantis.com/v1beta1
kind: ClusterDeployment
metadata:
  name: aws-ue2
  namespace: kcm-system
  labels:
    k0rdent.mirantis.com/istio-role: child
    k0rdent.mirantis.com/kof-cluster-role: regional
spec:
  template: aws-standalone-cp-0-1-6
  credential: aws-cluster-identity-cred
  config:
    clusterIdentity:
      name: aws-cluster-identity
      namespace: kcm-system
    clusterAnnotations:
      # `template: aws-standalone-cp` provides a default storage class:
      # k0rdent.mirantis.com/kof-storage-class: ebs-csi-default-sc

    region: us-east-2

    controlPlaneNumber: 1
    controlPlane:
      instanceType: t3.large

    workersNumber: 3
    worker:
      instanceType: t3.xlarge
