apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ClusterDeployment
metadata:
  name: azure-westus3-child1
  namespace: kcm-system
  labels:
    k0rdent.mirantis.com/kof-storage-secrets: "true"
    k0rdent.mirantis.com/kof-cluster-role: child
    # Optional, auto-detected by location:
    # k0rdent.mirantis.com/kof-regional-cluster-name: azure-westus3
spec:
  template: azure-standalone-cp-0-1-5
  credential: azure-cluster-identity-cred
  config:
    clusterIdentity:
      name: azure-cluster-identity
      namespace: kcm-system

    # Any custom values, e.g. https://github.com/opencost/opencost-helm-chart/blob/main/charts/opencost/README.md#values
    # clusterAnnotations:
    #   k0rdent.mirantis.com/kof-collectors-values: |
    #     opencost:
    #       opencost:
    #         exporter:
    #           replicas: 2

    subscriptionID: AZURE_SUBSCRIPTION_ID
    location: westus3

    controlPlaneNumber: 1
    controlPlane:
      vmSize: Standard_A4_v2

    workersNumber: 3
    worker:
      vmSize: Standard_A4_v2
