{{- if .Values.kcm.monitoring }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: flux-metrics-monitor
  namespace: {{ .Release.Namespace }}
spec:
  podMetricsEndpoints:
    - path: /metrics
      port: http-prom
      scheme: http
      interval: 30s
  namespaceSelector:
    matchNames:
      - {{ .Values.kcm.namespace }}
  selector: 
    matchExpressions:
    - key: app
      operator: In
      values:
      - helm-controller
      - source-controller
      - kustomize-controller
      - notification-controller
      - image-automation-controller
      - image-reflector-controller
{{- end }}
