{{- if .Values.kcm.monitoring }}
---
aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        kube-state-metrics/aggregate-to-manager: "true"
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-state-metrics-aggregated-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    kube-state-metrics/aggregate-to-manager: "true"
  name: kube-state-metrics-custom-resource-capi
rules:
  - apiGroups:
      - addons.cluster.x-k8s.io
    resources:
      - clusterresourcesets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - bootstrap.cluster.x-k8s.io
    resources:
      - kubeadmconfigs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - cluster.x-k8s.io
    resources:
      - clusterclasses
      - clusters
      - machinedeployments
      - machinehealthchecks
      - machinepools
      - machines
      - machinesets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - controlplane.cluster.x-k8s.io
    resources:
      - kubeadmcontrolplanes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - infrastructure.cluster.x-k8s.io
    resources:
      - devclusters
      - devmachines
      - dockerclusters
      - dockermachines
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ipam.cluster.x-k8s.io
    resources:
      - ipaddressclaims
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - runtime.cluster.x-k8s.io
    resources:
      - extensionconfigs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - source.toolkit.fluxcd.io
      - kustomize.toolkit.fluxcd.io
      - helm.toolkit.fluxcd.io
      - notification.toolkit.fluxcd.io
      - image.toolkit.fluxcd.io
    resources:
      - gitrepositories
      - buckets
      - helmrepositories
      - helmcharts
      - ocirepositories
      - kustomizations
      - helmreleases
      - alerts
      - providers
      - receivers
      - imagerepositories
      - imagepolicies
      - imageupdateautomations
    verbs: [ "list", "watch" ]
{{- end }}
