{
 "title": "Cluster Deployments Events",
 "description": "Cluster Deployments Events",
 "tags": [
  "Logs",
  "Kubernetes",
  "Events"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "datasource",
    "label": "datasource",
    "query": "victoriametrics-logs-datasource"
   },
   {
    "name": "cluster_deployment",
    "label": "cluster_deployment",
    "query": {
     "query": "k8s.object.kind:=\"ClusterDeployment\""
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "k8s.object.name:~\"$cluster_deployment\""
    }
   },
   {
    "name": "linked_object",
    "label": "linked_object",
    "query": {
     "query": "k8s.object.name:~\"$cluster_deployment\""
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Deployments Events - Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Events Details",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "k8s.namespace.name:~\"$namespace\"\nk8s.object.kind:$linked_object\nk8s.object.name:$cluster_deployment\nk8s.event.count:>=0"
    }
   ]
  },
  { "title": "Cluster Deployments - Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Overview",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "k8s.namespace.name:~\"$namespace\"\nk8s.object.name:$cluster_deployment\nk8s.object.kind:$linked_object\nk8s.event.count:>=0\n| stats by (severity) count()",
     "legendFormat": "{{`{{severity}}`}}"
    }
   ]
  },
  {
   "title": "Events by Reason",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "k8s.namespace.name:~\"$namespace\"\nk8s.object.name:$cluster_deployment\nk8s.object.kind:$linked_object\nk8s.event.count:>=0\n| stats by (k8s.event.reason) count()",
     "legendFormat": "{{`{{k8s.event.reason}}`}}"
    }
   ]
  }
 ]
}