{{- if .Values.kof.instrumentation.enabled }}
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: kof-instrumentation
  namespace: {{ .Release.Namespace }}
spec:
  exporter:
    endpoint: "http://{{ .Release.Name}}-node-exporter-collector:4318"
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  go:
    image: ghcr.io/open-telemetry/opentelemetry-go-instrumentation/autoinstrumentation-go:v0.19.0-alpha
    resourceRequirements:
      {{- toYaml .Values.kof.instrumentation.resources | nindent 6 }}
{{- end }}
