{{- if and .Values.jaeger.enabled .Values.jaeger.ingress.enabled }}
  {{- $username := randAlpha (.Values.global.random_username_length | int) }}
  {{- $password := randAlpha (.Values.global.random_password_length | int) }}
  {{- $secret := lookup "v1" "Secret" .Release.Namespace .Values.jaeger.security.credentials_secret_name }}
  {{- if $secret }}
    {{- $username = $secret.data.username | b64dec }}
    {{- $password = $secret.data.password | b64dec }}
  {{- end }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.jaeger.security.credentials_secret_name }}
  namespace: {{ .Release.Namespace }}
stringData:
  username: {{ $username | quote }}
  password: {{ $password | quote }}
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.jaeger.security.htpasswd_secret_name }}
  namespace: {{ .Release.Namespace }}
data:
  auth: {{ htpasswd $username $password | b64enc }}
type: Opaque
{{- end }}
