{{- range $name, $value := .Values.kcm.kof.clusterProfiles }}
{{- /* Distributing secrets to clusters automatically*/}}
---
apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: {{ $name }}
spec:
  clusterSelector:
    matchLabels: {{ $value.matchLabels | toYaml | nindent 6 }}
  templateResourceRefs:
    {{- range $value.secrets }}
    - identifier: secret-{{ . }}
      resource:
        apiVersion: v1
        kind: Secret
        name: {{ . }}
        namespace: {{ $.Release.Namespace }}
    {{- end }}
  policyRefs:
    {{- range $value.secrets }}
    - kind: ConfigMap
      name: secret-template-{{ . }}
      namespace: {{ $.Release.Namespace }}
    {{- end }}
{{- range $value.secrets }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: secret-template-{{ . }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    projectsveltos.io/template: "true"
data:
  secret.yaml: |
    {{` {{ copy "`}}secret-{{ . }}{{`" }} `}}
{{- end }}
{{- end }}
